server:
  port: 80
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_bot_first
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: never
  servlet:
    multipart:
      max-request-size: 20MB
      max-file-size: 20MB

telegram_bot_username: bekhruz_master_bot
telegram_bot_botToken: 5163744243:AAEuFOf3fQ-K5RJiGJzGVFuWKKTf4bzloZE



